--LOADING DATASET
CREATE TABLE Sales(
	OrderID VARCHAR(50),
	Date Date,
	CustomerID VARCHAR(50),
	Product VARCHAR(50),
	Quantity INT,
	UnitPrice NUMERIC,
	ShippingAddress VARCHAR(100),
	PaymentMethod VARCHAR(50),
	OrderStatus VARCHAR(50),
	TrackingNumber VARCHAR(50),
	ItemsInCart INT,
	CouponCode VARCHAR(50),
	ReferralSource VARCHAR(50),
	TotalPrice NUMERIC

);
--show all orders
SELECT * FROM SALES;

--show all orders where products is 'Laptop'
SELECT *
FROM sales
WHERE Product = 'Laptop';


-- show all orders that were delivered
SELECT *
FROM Sales
WHERE OrderStatus = 'Delivered';

--show all orders where quantity is greater than 3
SELECT *
FROM Sales
WHERE itemsincart > 3;

--SHOW ALL ORDERS Paid with creditcard
SELECT *
FROM Sales
WHERE PaymentMethod = 'Credit Card';

--SHOW ALL ORDERS THAT WERE RETURNED OR CANCELLED
SELECT *
FROM Sales
WHERE OrderStatus = 'Cancelled' and 'Returned';

--show all orders where NO coupon code was used
SELECT *
FROM Sales
WHERE CouponCode IS Null;

--show all orders where coupon code was used
SELECT *
FROM Sales
WHERE CouponCode IS NOT NULL;

--SHOW ALL ORDERS SORTED BY TOTAL PRICE FROM HIGHEST TO LOWEST
SELECT *
FROM Sales
ORDER BY TotalPrice DESC;

--HOW MAny orders were placed for each product
SELECT
	Product,
	Count(OrderID) 
FROM Sales
GROUP BY 1
ORDER BY 2;

--TOTAL REVENUE GENERATED BY EACH PRODUCTS
SELECT
	Product,
	SUM(TotalPrice) 
FROM Sales
GROUP BY 1
ORDER BY 2;

--HOW MANY ORDERS CAME FROM EACH REFERRED SOURCE
SELECT
	ReferralSource,
	Count(OrderID)  
FROM Sales
GROUP BY 1
ORDER BY 2 DESC;

--AVERAGE UNIT PRICE PER PRODUCT
SELECT
	Product,
	AVG(UnitPrice)
From Sales
GROUP BY 1
ORDER BY 2 DESC;

--SHOW ALL ORDERS  THAT ARE PENDING
SELECT *
FROM Sales
WHERE OrderStatus = 'Pending';

---WHAT IS THE TOTAL REVENUE FOR ALL DELIVERED PRODUCT
SELECT
	PRODUCT,
	SUM(TotalPrice) TOTALREVNUE
FROM Sales
GROUP BY 1
ORDER BY 2

--WHICH PAYMENT METHPOD BROUGHT IN THE MOST REVENUE
SELECT
	PaymentMethod,
	SUM(TotalPrice) TOTALREVNUE
FROM Sales
GROUP BY 1
ORDER BY 2

--TOTAL REVENUE PER ORDER STATUS
SELECT
	OrderStatus,
	SUM(TotalPrice) TOTALREVENUE
FROM Sales
GROUP BY 1
ORDER BY 2;

